spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${NOTIFICATION_SERVICE_KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
server:
  port: ${NOTIFICATION_SERVICE_SERVER_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health, info
