spring:
  application:
    name: transaction-service
  data:
    redis:
      host: ${TRANSACTION_SERVICE_REDIS_HOST}
      port: ${TRANSACTION_SERVICE_REDIS_PORT}
  datasource:
    url: ${TRANSACTION_SERVICE_DATASOURCE_URL}
    username: ${TRANSACTION_SERVICE_DATASOURCE_USERNAME}
    password: ${TRANSACTION_SERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${TRANSACTION_SERVICE_KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: transaction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: ${TRANSACTION_SERVICE_SERVER_PORT}

account:
  service:
    url: ${TRANSACTION_SERVICE_ACCOUNT_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
