spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${API_GATEWAY_REDIS_HOST}
      port: ${API_GATEWAY_REDIS_PORT}
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Account service routes
            - id: account-service
              uri: ${API_GATEWAY_ACCOUNT_SERVICE_URI}
              predicates:
                - Path=/api/v1/accounts/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 25

            # transaction service routes
            - id: transaction-service
              uri: ${API_GATEWAY_TRANSACTION_SERVICE_URI}
              predicates:
                - Path=/api/v1/transactions/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 25

            # payments service routes
            - id: payment-service
              uri: ${API_GATEWAY_PAYMENT_SERVICE_URI}
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 15

server:
  port: ${API_GATEWAY_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway