spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_SERVICE_DATASOURCE_URL}
    username: ${PAYMENT_SERVICE_DATASOURCE_USERNAME}
    password: ${PAYMENT_SERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    #just producer for the payment since we are just publishing in payment service
  kafka:
    bootstrap-servers: ${PAYMENT_SERVICE_KAFKA_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: ${PAYMENT_SERVICE_SERVER_PORT}

# razorpay configuration
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret:

management:
  endpoints:
    web:
      exposure:
        include: health,info

