spring:
  application:
    name: account-service
  datasource:
      url: ${ACCOUNT_SERVICE_DATASOURCE_URL}
      username: ${ACCOUNT_SERVICE_DATASOURCE_USERNAME}
      password: ${ACCOUNT_SERVICE_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${ACCOUNT_SERVICE_KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

server:
  port: ${ACCOUNT_SERVICE_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus